default_platform :ios

platform :ios do

  desc "Run all the tests"
  lane :test do
    scan(
      device: "iPhone 7 (10.0)",
      workspace: "JTDataStructures.xcworkspace",
      scheme: "JTDataStructures"
    )
  end
end